// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {settings} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:string):Promise<download.Download>;

export function CancelDownload(arg1:number):Promise<void>;

export function GetAllDownloads():Promise<Array<download.Download>>;

export function GetDownloadsByStatus(arg1:string):Promise<Array<download.Download>>;

export function GetSettings():Promise<settings.Settings>;

export function PauseDownload(arg1:number):Promise<void>;

export function RemoveDownload(arg1:number,arg2:boolean):Promise<void>;

export function ResumeDownload(arg1:number):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<settings.Settings>;
