// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddDownload'](arg1, arg2, arg3);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function GetAllDownloads() {
  return window['go']['app']['App']['GetAllDownloads']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetDownloadsByStatus(arg1) {
  return window['go']['app']['App']['GetDownloadsByStatus'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function RemoveDownload(arg1, arg2) {
  return window['go']['app']['App']['RemoveDownload'](arg1, arg2);
}

export function ResumeDownload(arg1) {
  return window['go']['app']['App']['ResumeDownload'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
